;;*****************************************************************************
;;*****************************************************************************
;;  FILENAME: TempBuf.inc
;;  Version: 1.3, Updated on 2013/5/19 at 10:43:26
;;  Generated by PSoC Designer 5.4.2946
;;
;;  DESCRIPTION: Assembler declarations for the Counter8 user module interface
;;-----------------------------------------------------------------------------
;;  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
;;*****************************************************************************
;;*****************************************************************************

include "m8c.inc"


;--------------------------------------------------
; Constants for TempBuf API's.
;--------------------------------------------------

TempBuf_CONTROL_REG_START_BIT:             equ 0x01    ; Control register start bit
TempBuf_INT_REG:                           equ 0x0e1
TempBuf_INT_MASK:                          equ 0x02


;--------------------------------------------------
; Register Address Constants for TempBuf
;--------------------------------------------------

TempBuf_DATA_0_REG:                    equ 0x24   ; DR0 register
TempBuf_DATA_1_REG:                    equ 0x25   ; DR1 register
TempBuf_DATA_2_REG:                    equ 0x26   ; DR2 register
TempBuf_CONTROL_REG:                   equ 0x27   ; Control register
TempBuf_FUNC_REG:                      equ 0x24   ; Function register
TempBuf_INPUT_REG:                     equ 0x25   ; Input register
TempBuf_OUTPUT_REG:                    equ 0x26   ; Output register


;--------------------------------------------------
; TempBuf Macro 'Functions'
;--------------------------------------------------

   macro TempBuf_Start_M
   or    reg[TempBuf_CONTROL_REG],  TempBuf_CONTROL_REG_START_BIT
   endm

   macro TempBuf_Stop_M
   and   reg[TempBuf_CONTROL_REG], ~TempBuf_CONTROL_REG_START_BIT
   endm

   macro TempBuf_EnableInt_M
   M8C_EnableIntMask TempBuf_INT_REG, TempBuf_INT_MASK
   endm

   macro TempBuf_DisableInt_M
   M8C_DisableIntMask TempBuf_INT_REG, TempBuf_INT_MASK
   endm


; end of file TempBuf.inc
